### ISSUE TITLE
Should I use?

### ISSUE THREAD

**Issue by danilovaz** [sindresorhus/broccoli-stylus#6]
@sindresorhus this plugin is actually maintained? I'm using Ember.js and I have some stylus tasks in gulp, but I'm trying to move this to broccoli. So I find your plugin :smile:

**Comment by sindresorhus** [comment]
It's maintained.

-

In the future please don't waste maintainers time with such unnecessary issue. You can easily infer maintainability from commit activity. Every issue like this takes time away from actually maintaining projects.

**Comment by danilovaz** [comment]
Makes sense. But I must admit that my question originated in an [open issue since 2014](https://github.com/sindresorhus/broccoli-stylus/issues/1). So my concern whether the use of this plugin is actually maintained and if I can use it or maybe help with. First I need to think about not waste my time to use something that perhaps was not being maintained. My apologies for this issue unnecessary. :smile:
